### ISSUE TITLE
Finding the right Client implementation shouldn't be hardcoded

### ISSUE THREAD

**Issue by kanuku** [zalando/kontrolletti#10]
**How it works now**  
When `Kontrolletti` communicates with Stash and Github.com it uses the [SCM logic](https://github.com/zalando-bus/kontrolletti/blob/develop/app/v1/client/SCM.scala).  The SCM logic,  decides, based on the domain of the url, which implementation to use: 
* if the url is  https://`github.com`/zalando-bus/kontrolletti then the `Github` logic  (`github.com`) is used.
* otherwise If the url is https://`stash.zalando.net`/rest/api/1.0/projects/doc/repos/ci-cd/commits then Stash logic (`stash.zalando.net`) is used.

**The problem**
If the the domain of stash changes to somehting like stash.zalan.do, then we have to change the hardcoded domain in the SCM logic.

**Suggestion**
Kontrolletti should get the logic from either an external datastore or a configuration file.
something like
```json
clients:[ 
{ client: github
  domains:[{github.com, github-enterprise.zalan.do, , github-enterprise.zalando.net}]
},
{ client: stash
  domains:[{stash.zalando.net, stash.zalan.do}]
}
]
```

**Comment by lotharschulz** [comment]
estimate: 5
