### ISSUE TITLE
Support special chars, e.g. "~" in repo urls

### ISSUE THREAD

**Issue by harti2006** [zalando/kontrolletti#120]
Some repository urls contain a "~". Kontrolletti responds with `400 Bad Request` when trying to normalize such repository urls.

## Expected behavior

Special characters should be supported in repository urls (as long as they are [valid URI chars](http://stackoverflow.com/questions/1547899/which-characters-make-a-url-invalid/1547940#1547940))

**Comment by kanuku** [comment]
Hi, at first support for private repositories were not supported.
As of today, private repositories should be supported except for repositories residing on github.com. 
For github.com a whitelist(`client.scm.github.allowedProjects`) can be configured for projects from a certain owner/organization.

**Comment by kanuku** [comment]
New test-cases
https://stash.com/scm/~lschumacher/20questions.git
https://git@stash.com:7999/~kzimnicki/stock-chart-demo.git
https://stash.com/scm/~lnait/coding-game.git
https://stash.com/scm/~htres/20questions.git
