### ISSUE TITLE
Filter commits by "since" and "until"

### ISSUE THREAD

**Issue by harti2006** [zalando/kontrolletti#121]
`/api/hosts/{host}/projects/{project}/repos/{repository}/commits` provides optional parameters to filter commits after (**since**), and commits before (**until**) a certain one.

Using these parameters separately works as expected, but using them in conjunction does always return an empty result (404 Not Found). In other words: *Show me all commits between commit A and commit B* does not work.

**Comment by kanuku** [comment]
@harti2006 You are right, since and untill parameters were switched, hence the 404.
