### ISSUE TITLE
assume techjira as default custom protocol for commit messages

### ISSUE THREAD

**Issue by taojang** [zalando/kontrolletti#177]
In case the complete commit message does not start with either:
* https://
* http://
* offline:
* techjira:
* GH-  

assume *techjira:* is meant.

**Comment by hjacobs** [comment]
Hmm, that's not enough --- "#123" should be read as GitHub issue ID.

**Comment by taojang** [comment]
@hjacobs this issue is only about widely used jira protocol like ```BA-777```, which is not in the old specification. Hashtag is covered already :)

**Comment by hjacobs** [comment]
@taojang ok, thanks :smile:

**Comment by taojang** [comment]
regarding the [comment](https://github.com/zalando/kontrolletti/pull/178#discussion_r59718231) for adding constrain of ensuring the ticket appear at the beginning of commit message:

We can not do that because of the merge commit. Usually and especially in stash, people tend to use default message when creating a PR, then the ticket(s) will not appear at the beginning of the message.

Additionally I dislike manual defining the samples for testing. I will replace them with property based testing if I could find a way to generate useful test data.

In the future we should rewrite this part also. Using regex is straight forward and simple, but it's hard for me to read, especially when couple of them mixed together. More importantly, there is no history that could explain why parsing failed. We need to use something else like ```fastparse``` or equvilant solution.

**Comment by taojang** [comment]
#179 created
