### ISSUE TITLE
Url prefixed with the "git:" protocol are not recognized

### ISSUE THREAD

**Issue by harti2006** [zalando/kontrolletti#185]
### git@github.com/zalando/kontrolletti.git
`curl -H "Authorization: Bearer $(zign token)" -X HEAD -v https://kontrolletti.automata.zalan.do/api/repos/git%40github.com%3Azalando%2Fkontrolletti.git`
works as expected (returns the `X-Normalized-Repository-URL` header)

### git:git@github.com/zalando/kontrolletti.git
`curl -H "Authorization: Bearer $(zign token -n kontrolletti)" -X HEAD -v https://kontrolletti.automata.zalan.do/api/repos/git%3Agit%40github.com%3Azalando%2Fkontrolletti.git`
Returns just a 404 status, without the header.

**Comment by taojang** [comment]
fixed via #186
