### ISSUE TITLE
Check if two URLs belong to the same repository

### ISSUE THREAD

**Issue by prayerslayer** [zalando/kontrolletti#27]
I would like to submit two URLs and know if those belong to the same repository.

For instance:

    Input: git@github.com:zalando/kontrolletti.git, https://github.com/zalando/kontrolletti
    Output: true

Background: In YOUR TURN I'd like to display a warning if the deployment artifact wasn't built from the applications main repository (as opposed to a fork, for instance).

Do you think this could be something you would want to integrate in Kontrolletti?

**Comment by kanuku** [comment]
The logic for parsing different urls is [already in place](https://github.com/zalando/kontrolletti/blob/develop/test/util/GithubUrlParserTest.scala).
I am thinking about a url for kontrolletti-specific validations, something similar to:  
**Request:**
`POST` https://kontrolletti/api/validations
```json
{
type: "repos",
operation: "equals",
url1: "git@github.com:zalando/kontrolletti.git",
url2: "https://github.com/zalando/kontrolletti"
} 
```
**Response:**
`200`
***

**Comment by lotharschulz** [comment]
estimation: 5

**Comment by kanuku** [comment]
@prayerslayer 
The rest api has been extended with A HEAD operation that can be used to normalize the repository URL's.

**Endpoint**: https://kontrolletti/api/repos

**Results:**
**HTTP 200** - Resource is normalized and `probably` available on the server.
**HTTP 301** - Resource can might be available under a different URI. **+** An extra header with the normalized repository URL can be found key = **Normalized-Repository-Identifier**.
**HTTP 400** - Invalid repository URL.

===
##### Example 1
Returns **200**  with an already normalized URL  `https://github.com/zalando/kontrolletti`
```sh
curl -X HEAD  -i http://localhost:9000/api/repos/https%3A%2F%2Fgithub.com%2Fzalando%2Fkontrolletti
# Result
HTTP/1.1 200 OK
Content-Length: 0
```
===
##### Example 2
Returns **301** with a not normalized URL   `git@github.com:zalando/kontrolletti.git`
```sh
curl -X HEAD  -i http://localhost:9000/api/repos/git%40github.com%3Azalando%2Fkontrolletti.git
HTTP/1.1 301 Moved Permanently
Location: /api/repos/https%253A%252F%252Fgithub.com%252Fzalando%252Fkontrolletti
Normalized-Repository-Identifier: https://github.com/zalando/kontrolletti
Content-Length: 0
```
===
##### Example 3
Returns **400** with an invalid URL  `abc`
```sh
curl -X HEAD  -i http://localhost:9000/api/repos/abc
HTTP/1.1 400 Bad Request
Content-Type: text/plain; charset=utf-8
Content-Length: 19

Could not parse abc
```

**Comment by prayerslayer** [comment]
Looks great :+1:
